


-- WHEN CASE


USE PRACTICE

SELECT *,
CASE
WHEN ORDER_AMOUNT <=6000 THEN "LOW_AMT"
WHEN ORDER_AMOUNT  <=9000  THEN "MID_AMT"
WHEN ORDER AMOUNT > 9000 THEN "HIGH_AMT"
ELSE ORDER_AMOUNT
END AS ABC
FROM ORDERS;


SELECT  
SUM(CASE WHEN SALARY <= 8000 THEN 1
 ELSE 0 END) AS below_8000,
SUM(CASE WHEN SALARY > 8000 THEN 1 
ELSE 0 END) AS above_8000
FROM EMPLOYEES;


SELECT * FROM EMPLOYEES;
SELECT 
SUM(CASE WHEN EXPERIENCE < 3 THEN 1
ELSE 0
END) ,
SUM(CASE WHEN  EXPERIENCE < 6 AND EXPERIENCE >3 THEN 1
ELSE 0
END ),
SUM(CASE WHEN EXPERIENCE > 6  THEN 1
ELSE 0
END) 
FROM EMPLOYEES;
