

SELECT * FROM (
SELECT *, ROW_NUMBER() OVER() AS RN FROM PAYMENTS) AS TBL
WHERE RN >= 100 ;


WITH XYZ AS
(
SELECT *, ROW_NUMBER() OVER() AS RN FROM PAYMENT
)
SELECT * FROM XYZ;



WITH XYZ AS
(
SELECT *, SUM(AMOUNT) OVER(PARTITION BY CUSTOMER_ID) AS TOTAL FROM PAYMENT
)
SELECT * FROM XYZ


RANKING_XYZ  AS
(
SELECT * , DENSE_RANK()  OVER(ORDER BY TOTAL ASC) AS RANKING
FROM XYZ)
SELECT * FROM RANKING_XYZ;