
use test




SELECT * FROM SALES

-- Har order me products ka total price (window use karke)

SELECT *,
SUM(QUANTITY*PRICE)  OVER(PARTITION BY ORDER_ID) FROM SALES


-- Har order me highest price product
SELECT * FROM (
SELECT *,
DENSE_RANK()  OVER(PARTITION BY PRODUCT_NAME ORDER BY PRICE DESC) AS LT FROM SALES)  LA
WHERE LT = 1;


-- 6. Product-wise sales running total

SELECT *, 
SUM(PRICE) OVER(PARTITION BY PRODUCT_NAME ORDER BY PRICE)
FROM SALES

use company_db
SELECT * FROM EMPLOYEES
-- Har department me salary ke hisaab se rank nikalo

SELECT *, RANK()  OVER(PARTITION BY DEPARTMENT ORDER BY SALARY DESC) FROM EMPlOYEES


-- Lowest salary employee in each department
SELECT * FROM(
SELECT * , DENSE_RANK() OVER(PARTITION BY DEPARTMENT ORDER BY SALARY ASC) AS KL FROM EMPLOYEES)  DJH
WHERE  KL = 1;


-- Har employee ke saath uske department ka total salary show karo
SELECT *, SUM(SALARY) OVER(PARTITION BY DEPARTMENT )  FROM EMPLOYEES


-- Joining date ke hisaab se running total salary
USE COMPANY_DB

SELECT * FROM EMPLOYEES
SELECT 
    *,
    SUM(SALARY) OVER (ORDER BY JOINING_DATE) AS RUNNING_TOTAL
FROM EMPLOYEES;



SELECT 
    *,
    LAG(SALARY) OVER (ORDER BY JOINING_DATE) AS PREV_SALARY
FROM EMPLOYEES;

SELECT 
    emp_id,
    name,
    salary,
    LEAD(salary) OVER (ORDER BY joining_date) AS next_salary
FROM employees;


-- SALARY GROWTH
SELECT 
    emp_id,
    name,
    salary,
    LAG(salary) OVER (ORDER BY joining_date) AS prev_salary,
    salary - LAG(salary) OVER (ORDER BY joining_date) AS salary_growth
FROM employees;



-- Har department me salary percentile (PERCENT_RANK)
SELECT * , PERCENT_RANK()  OVER(PARTITION BY DEPARTMENT ORDER BY SALARY ) FROM EMPLOYEES



-- NTILE(3) use karke employees ko 3 groups me divide karo
SELECT 
    emp_id,
    name,
    department,
    salary,
    NTILE(3) OVER (ORDER BY salary DESC) AS salary_group
FROM employees;



-- Har city me top performer (highest salary)
SELECT * FROM (
SELECT * , PERCENT_RANK()  OVER(PARTITION BY CITY ORDER BY SALARY ASC) AS PERFORMANCE FROM EMPLOYEES) AS DFG
WHERE PERFORMANCE > 0.90;


-- Production department ka avg vs actual salary difference
SELECT 
    emp_id,
    name,
    department,
    salary,
    AVG(salary) OVER (PARTITION BY department) AS dept_avg,
    salary - AVG(salary) OVER (PARTITION BY department) AS salary_diff
FROM employees
WHERE department = 'Production';


-- Q1. Salary Category banao

-- Salary < 28000 → "Low"
-- 28000–32000 → "Medium"

-- 32000 → "High"


SELECT *,
CASE
WHEN SALARY  < 28000 THEN "LOW"
WHEN SALARY  > 28000 AND SALARY < 32000  THEN "MEDIUM"
END
FROM EMPLOYEES;


                --     
-- Q5. Count karo

-- Kitne employees salary > 30000
-- Kitne ≤ 30000

-- 👉 Output columns:

-- high_salary_count
-- low_salary_count

SELECT * FROM EMPLOYEES 

SELECT 
SUM(CASE WHEN SALARY < 3000 THEN 1
ELSE 0 END),
SUM(CASE WHEN SALARY> 3000 THEN 1
ELSE 0 END)
FROM EMPLOYEES;


-- Q6. Department wise salary distribution

-- Count of employees with salary > 30000 per department


SELECT 
SUM(CASE WHEN SALARY < 3000 THEN 1
ELSE 0 END),
SUM(CASE WHEN SALARY> 3000 THEN 1
ELSE 0 END)
FROM EMPLOYEES;


SELECT 
    DEPARTMENT,
    SUM(CASE WHEN SALARY > 30000 THEN 1 ELSE 0 END) AS high_salary_count
FROM EMPLOYEES
GROUP BY DEPARTMENT;


-- Q7. Avg salary difference

-- Har employee ka salary vs overall avg difference
-- CASE se bata:
-- Above Avg
-- Below Avg

SELECT *,
CASE WHEN DIFF > 0  THEN "ABOVE AVG"
WHEN DIFF < 0   THEN "BELOW AVG"
ELSE " EQUAL AVG"
END  AS SALARY_STATUS
FROM (
SELECT *, 
SALARY - AVG(SALARY) OVER() AS DIFF
FROM EMPLOYEES) AS VND


Q9. City + Salary Combo

Surat + salary > 30000 → "Premium Surat Employee"
Vapi + salary > 30000 → "Premium Vapi Employee"
Baaki → "Normal"


SELECT *, CASE
WHEN  CITY = "SURAT" AND SALARY > 30000 THEN "PRIMIUM SURAT EMPLOYEES"
WHEN CITY = "VAPI"  AND  SALARY > 30000 THEN "PEIMIUM VAPI EMPLOYEES"
ELSE "NORMAL" END 
FROM(
SELECT * FROM (
SELECT CITY ,SALARY
FROM EMPLOYEES 
GROUP BY CITY ,SALARY) AS BJHH
WHERE CITY IN ("SURAT","VAPI") ) AS KJBKJ




USE PRACTICE
SELECT * FROM EMPLOYEES;
SELECT * FROM  ORDERS;

SELECT * FROM EMPLOYEES E
LEFT JOIN ORDERS  O
ON E.EMP_ID = O.EMP_ID;


-- 6. Show all employees with total order amount

SELECT E.NAME,
SUM(O.ORDER_AMOUNT),
E.EMP_ID
FROM EMPLOYEES E
LEFT JOIN  ORDERS O
ON E.EMP_ID = O.EMP_ID
GROUP BY E.NAME , E.EMP_ID  


-- 7. Find department-wise total order amount

SELECT  E.DEPARTMENT,
E.EMP_ID,
SUM(ORDER_AMOUNT)
FROM EMPLOYEES E
LEFT JOIN  ORDERS O
ON E.EMP_ID = O.EMP_ID 
GROUP BY E.DEPARTMENT

SELECT * FROM EMPLOYEES;
SELECT* FROM ORDERS


 -- Find employee with highest order amount

SELECT 
    O.EMP_ID,
    E.NAME,
    O.ORDER_AMOUNT
FROM ORDERS O
LEFT JOIN EMPLOYEES E
ON E.EMP_ID = O.EMP_ID
WHERE O.ORDER_AMOUNT = (
    SELECT MAX(ORDER_AMOUNT)
    FROM ORDERS
);





USE SAKILA
SELECT * FROM FILM;
SELECT * FROM LANGUAGE;
-- SELECT * FROM  FILM_TEXT
-- SELECT * FROM  CATEGORY
-- SELECT * FROM STAFF


SELECT F.TITLE,
F.LANGUAGE_ID,
L.NAME
FROM FILM F
LEFT JOIN  LANGUAGE L
ON F.LANGUAGE_ID = L.LANGUAGE_ID;



SELECT * FROM CUSTOMER;
SELECT * FROM PAYMENT;
SELECT * FROM CITY;
SELECT * FROM  ADDRESS;
SELECT * FROM STAFF;
SELECT * FROM RENTAL;
SELECT * FROM STORE;
SELECT * FROM INVENTRY;


-- LIST ALL CUSTOMER WITH THEIR COUNTRY NAME 
SELECT
C.FIRST_NAME,
CY.COUNTRY
FROM CUSTOMER C
LEFT JOIN ADDRESS A
ON C.ADDRESS_ID = A.ADDRESS_ID
LEFT JOIN CITY CT
ON A.CITY_ID = CT.CITY_ID
LEFT JOIN COUNTRY CY
ON CY.COUNTRY_ID = CT.COUNTRY_ID;



-- 10. Find employees whose salary is greater than their total orders
USE PRACTICE;
SELECT * FROM  EMPLOYEES;
SELECT * FROM ORDERS;

SELECT * FROM(
SELECT E.EMP_ID,
E.SALARY,
SUM(O.ORDER_AMOUNT) AS TOTAL,
E.NAME
FROM EMPLOYEES E
LEFT JOIN ORDERS O
ON E.EMP_ID = O.EMP_ID
GROUP BY  E.EMP_ID,E.NAME,E.SALARY) AS BHHK
WHERE TOTAL < SALARY


-- 11. Find employees who placed more than 1 order

SELECT
E.NAME,
COUNT(O.EMP_ID) AS COUNT,
FROM ORDERS O
LEFT JOIN  EMPLOYEES E
ON E.EMP_ID = O.EMP_ID
GROUP BY E.NAME , COUNT


-- 12. Show employees with latest order date
USE PRACTICE
SELECT * FROM EMPLOYEES;
SELECT * FROM ORDERS;

SELECT e.name,
MAX(o.order_date) AS latest_order
FROM employees e
JOIN orders o
ON e.emp_id = o.emp_id
GROUP BY e.emp_id, e.name;


-- Find departments where total order amount > 15000
SELECT * FROM EMPLOYEES;
SELECT * FROM ORDERS;

SELECT E.DEPARTMENT,
SUM(O.ORDER_AMOUNT)
FROM EMPLOYEES E
LEFT JOIN ORDERS O
ON E.EMP_ID = O.EMP_ID
GROUP BY E.DEPARTMENT 
HAVING SUM(O.ORDER_AMOUNT) > 15000
USE PRACTICE
-- 14. Show employees whose order amount is above average order amount


SELECT * FROM (
SELECT *, CASE
WHEN ORDER_AMOUNT > (SELECT AVG(ORDER_AMOUNT)  FROM ORDERS) THEN 1 
ELSE 0 
END AS MLL
FROM(
SELECT O.ORDER_AMOUNT,
E.EMP_ID,
E.NAME
FROM ORDERS O
LEFT JOIN EMPLOYEES E
ON E.EMP_ID = O.EMP_ID) AS JKBK) AS JBK
WHERE MLL = 1;


-- Find top 3 employees based on total order amount

SELECT * FROM (
SELECT  SUM(O.ORDER_AMOUNT) AS TOTAL,
E.EMP_ID
FROM ORDERS O
LEFT JOIN EMPLOYEES E
ON E.EMP_ID = O.EMP_ID
GROUP BY E.EMP_ID) AS  DSB
ORDER BY TOTAL DESC
LIMIT 3


-- 17. Find employees from IT department who placed orders above 7000
use practice
select * from employees;
select * from orders;

select e.name,
e.emp_id,
e.department,
o.order_amount
from employees e
join orders  o
where department = "IT"  and  order_amount > 7000;






SELECT * , DENSE_RANK()  OVER(ORDER BY TOTAL DESC)
FROM(
SELECT E.DEPARTMENT,
SUM(O.ORDER_AMOUNT) AS TOTAL
FROM  ORDERS O
LEFT JOIN EMPLOYEES E
ON E.EMP_ID = O.EMP_ID
GROUP BY E.DEPARTMENT  ) AS BHJB ;

SELECT * FROM EMPLOYEES;
SELECT * FROM  ORDERS;



WITH CTE_NAME AS 
(SELECT
DEPARTMENT,ORDER_AMOUNT,
CASE
WHEN DEPARTMENT = "HR" THEN  "RECRUITER"
WHEN DEPARTMENT  = "FINANCE" THEN "CA"
WHEN DEPARTMENT = "IT" THEN "DA"
ELSE "NULL"
END AS UPDATEDNAME
FROM EMPLOYEES LEFT JOIN ORDERS
ON EMPLOYEES.EMP_ID = ORDERS.EMP_ID)

SELECT UPDATEDNAME,SUM(ORDER_AMOUNT)
FROM CTE_NAME
GROUP BY UPDATEDNAME



-- VIEW IS VIRTUAL TABLE THAT CREATE DATABASE IN STORING QUERY LOGIC IN DATABASE 


CREATE VIEW VIEW_EMP AS (
SELECT EMP_ID,NAME,DEPARTMENT,CITY FROM EMPLOYEES)


-- STORE QUERY KA DATA AND QUERY BOTH SAVE KARTA HAI

DELIMETER $$

CREATE PROCEDURE GETEMPLOYEESRLIST()
BEGIN  
     SELECT * FROM EMPLOYEES;
END $$     


DELIMETER;



USE PRACTICE
-- CITY WISE TOTAL RANK

SELECT  * FROM EMPLOYEES;


SELECT *, DENSE_RANK()  OVER(ORDER BY TOTAL DESC)
FROM(
SELECT SUM(SALARY) AS TOTAL , CITY
FROM EMPLOYEES
GROUP BY CITY ) AS JKN



WITH XYZ AS 
(
SELECT SUM(SALARY) AS TOTAL , CITY
FROM EMPLOYEES
GROUP BY CITY )

SELECT *, DENSE_RANK()  OVER(ORDER BY TOTAL DESC)
FROM XYZ


SELECT * FROM (
SELECT *,
CASE
WHEN  SALARY-(SELECT AVG(SALARY) FROM EMPLOYEES) > 0 THEN 1
ELSE 0
END AS BJH
FROM EMPLOYEES) AS NKJ
WHERE BJH = 1;


SELECT * FROM EMPLOYEES;
SELECT * FROM ORDERS;



SELECT  E.EMP_ID,
O.ORDER_AMOUNT
FROM EMPLOYEES E
LEFT JOIN  ORDERS O
ON E.EMP_ID = O.EMP_ID



SELECT EMP_ID ,NAME FROM EMPLOYEES
WHERE EMP_ID NOT IN  (SELECT EMP_ID FROM ORDERS) ;


SELECT * FROM(
SELECT  *, DENSE_RANK() OVER(PARTITION BY DEPARTMENT ORDER BY SALARY DESC) AS RANKS
FROM EMPLOYEES) AS KJK
WHERE RANKS <6;











