
-- rank , dense rank ,row number
-- rank skip duplicate values  ranking , dense rank does not skip the  duplicate value rank
SELECT *, ROW_NUMBER()  OVER() AS ROWNUM,
RANK() OVER(ORDER BY SALARY DESC) AS RANKS,
DENSE_RANK() OVER(ORDER BY SALARY DESC) AS DENSE_RANKS
FROM EMPLOYEES;


SELECT * FROM (
SELECT *, RANK() 
OVER(PARTITION BY CITY ORDER BY SALARY DESC) AS DENSE_RANKS
FROM EMPLOYEES) AS TBL
WHERE DENSE_RANKS = 2;


SELECT *,DENSE_RANK() OVER(ORDER BY SUMS DESC) AS DPS
FROM (SELECT *,SUM(SALARY) OVER(PARTITION BY DEPARTMENT) AS SUMS
FROM EMPLOYEES) AS KD;


SELECT * FROM (
SELECT *, DENSE_RANK() OVER(ORDER BY SALARY DESC) AS SLS
FROM EMPLOYEES) AS L 
WHERE SLS = 2 ;
