
use Practice;

SELECT * FROM employees;

SELECT DEPARTMENT,CITY,COUNT(*),SUM(SALARY),AVG(SALARY) FROM EMPLOYEES
WHERE EXPERIENCE > 2
GROUP BY DEPARTMENT,CITY;


-- Get employees with salary > 60000
SELECT * FROM employees;
WHERE salary > 60000;


-- Get employees from Delhi
SELECT * FROM EMPLOYEES
WHERE CITY = 'DELHI';


-- Get employees with experience > 5
SELECT * FROM EMPLOYEES
WHERE EXPERIENCE < 5;


-- Get IT department employees
SELECT * FROM EMPLOYEES
WHERE DEPARTMENT = 'IT';


-- Get employees NOT from Mumbai
SELECT * FROM EMPLOYEES
WHERE  CITY != 'MUMBAI';

-- Get employees with experience <= 3
SELECT * FROM EMPLOYEES
WHERE  EXPERIENCE <= 3;


-- Get employees from Delhi AND salary > 50000
SELECT * FROM EMPLOYEES
WHERE  SALARY > 50000 AND CITY = 'DELHI';



-- Get employees from Mumbai OR Pune
SELECT * FROM EMPLOYEES
WHERE   CITY = 'DELHI' OR CITY = 'PUNE';



-- Get employees whose name starts with 'A'
SELECT * FROM EMPLOYEES
WHERE   NAME LIKE 'A%';

-- Count employees in each department
SELECT DEPARTMENT,CITY,
COUNT(DEPARTMENT),SUM(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT,CITY;





SELECT CITY,
COUNT(DEPARTMENT)
FROM EMPLOYEES
GROUP BY CITY;

-- window  aggricate function  function

SELECT DEPARTMENT, SUM(SALARY) FROM EMPLOYEES
GROUP BY 1;
SELECT  *, SUM(SALARY) OVER()
FROM  EMPLOYEES;



SELECT  *, SUM(SALARY) OVER(PARTITION BY DEPARTMENT)
FROM  EMPLOYEES;



SELECT  *, SUM(SALARY) OVER(ORDER BY  EMP_ID)
FROM  EMPLOYEES;


SELECT  *, SUM(SALARY) OVER(ORDER BY CITY)
FROM  EMPLOYEES;


SELECT  *, SUM(SALARY) OVER(ORDER BY CITY)
FROM  EMPLOYEES;


SELECT  *, SUM(SALARY) OVER(PARTITION  BY CITY ORDER BY DEPARTMENT)
FROM  EMPLOYEES;



-- compute  cummulative sallary by department
-- avg salary per department without using groupby 


SELECT *,SUM(SALARY) OVER(PARTITION BY DEPARTMENT ORDER BY EMP_ID)
FROM EMPLOYEES;

SELECT *,AVG(SALARY) OVER(PARTITION BY DEPARTMENT)
FROM EMPLOYEES;


SELECT *,AVG(SALARY) OVER(),
SUM(SALARY) OVER(),
MIN(SALARY) OVER(),
MAX(SALARY) OVER(),
COUNT(SALARY) OVER()
FROM EMPLOYEES;


SELECT *,AVG(SALARY) OVER(PARTITION BY CITY),
SUM(SALARY) OVER(PARTITION BY CITY),
MIN(SALARY) OVER(PARTITION BY CITY),
MAX(SALARY) OVER(PARTITION BY CITY),
COUNT(SALARY) OVER(PARTITION BY CITY)
FROM EMPLOYEES;



-- rank , dense rank ,row number
-- rank skip duplicate values  ranking , dense rank does not skip the  duplicate value rank
SELECT *, ROW_NUMBER()  OVER() AS ROWNUM,
RANK() OVER(ORDER BY SALARY DESC) AS RANKS,
DENSE_RANK() OVER(ORDER BY SALARY DESC) AS DENSE_RANKS
FROM EMPLOYEES;


SELECT * FROM (
SELECT *, RANK() 
OVER(PARTITION BY CITY ORDER BY SALARY DESC) AS DENSE_RANKS
FROM EMPLOYEES) AS TBL
WHERE DENSE_RANKS = 2;


SELECT *,DENSE_RANK() OVER(ORDER BY SUMS DESC) AS DPS
FROM (SELECT *,SUM(SALARY) OVER(PARTITION BY DEPARTMENT) AS SUMS
FROM EMPLOYEES) AS KD;


SELECT * FROM (
SELECT *, DENSE_RANK() OVER(ORDER BY SALARY DESC) AS SLS
FROM EMPLOYEES) AS L 
WHERE SLS = 2 ;

select salary from emoloyees 
where salary < (select max(salary) from employees)
ORDER BY SALARY DESC

