



-- window function

SELECT DEPARTMENT, SUM(SALARY) FROM EMPLOYEES
GROUP BY 1;
SELECT  *, SUM(SALARY) OVER()
FROM  EMPLOYEES;



SELECT  *, SUM(SALARY) OVER(PARTITION BY DEPARTMENT)
FROM  EMPLOYEES;



SELECT  *, SUM(SALARY) OVER(ORDER BY  EMP_ID)
FROM  EMPLOYEES;


SELECT  *, SUM(SALARY) OVER(ORDER BY CITY)
FROM  EMPLOYEES;


SELECT  *, SUM(SALARY) OVER(ORDER BY CITY)
FROM  EMPLOYEES;


SELECT  *, SUM(SALARY) OVER(PARTITION  BY CITY ORDER BY DEPARTMENT)
FROM  EMPLOYEES;



-- compute  cummulative sallary by department
-- avg salary per department without using groupby 


SELECT *,SUM(SALARY) OVER(PARTITION BY DEPARTMENT ORDER BY EMP_ID)
FROM EMPLOYEES;

SELECT *,AVG(SALARY) OVER(PARTITION BY DEPARTMENT)
FROM EMPLOYEES;


SELECT *,AVG(SALARY) OVER(),
SUM(SALARY) OVER(),
MIN(SALARY) OVER(),
MAX(SALARY) OVER(),
COUNT(SALARY) OVER()
FROM EMPLOYEES;


SELECT *,AVG(SALARY) OVER(PARTITION BY CITY),
SUM(SALARY) OVER(PARTITION BY CITY),
MIN(SALARY) OVER(PARTITION BY CITY),
MAX(SALARY) OVER(PARTITION BY CITY),
COUNT(SALARY) OVER(PARTITION BY CITY)
FROM EMPLOYEES;
